# Generated by Django 2.0 on 2018-07-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0009_auto_20180530_2321'),
        ('viewers', '0002_auto_20180701_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.WallImages'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='information',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='marital_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.MartialStatus'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='place_work',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=85, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
