# Generated by Django 2.0 on 2018-07-04 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wall', '0009_auto_20180530_2321'),
        ('viewers', '0003_auto_20180702_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default=None, max_length=85, null=True)),
                ('place_work', models.CharField(blank=True, default=None, max_length=36, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=12)),
                ('information', models.TextField(blank=True, default=None, null=True)),
                ('marital_status', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.MartialStatus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
