# Generated by Django 2.0 on 2018-09-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewers', '0006_auto_20180915_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='avatar',
            field=models.FileField(upload_to='wall_images/'),
        ),
    ]
