# Generated by Django 2.0 on 2018-05-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WallImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wall_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WallImage',
                'verbose_name_plural': 'WallImage',
            },
        ),
        migrations.CreateModel(
            name='WallInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default=None, max_length=36, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=36, null=True)),
                ('information', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.WallImages')),
            ],
            options={
                'verbose_name': 'WallInformation',
                'verbose_name_plural': 'WallInformation',
            },
        ),
    ]
