# Generated by Django 2.0 on 2018-05-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20180529_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallimages',
            options={'verbose_name': 'Wall Image', 'verbose_name_plural': 'Wall Images'},
        ),
        migrations.AlterModelOptions(
            name='wallinformation',
            options={'verbose_name': 'Wall Information', 'verbose_name_plural': 'Wall Information'},
        ),
    ]
