# Generated by Django 2.0 on 2018-05-29 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20180529_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallinformation',
            name='social_networl',
        ),
        migrations.AddField(
            model_name='wallinformation',
            name='social_network',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.SocialNetworks'),
        ),
    ]
