# Generated by Django 2.0 on 2018-05-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_auto_20180529_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='martialstatus',
            old_name='name',
            new_name='status',
        ),
    ]
