# Generated by Django 2.0 on 2018-05-30 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_auto_20180530_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallinformation',
            name='social_networks',
        ),
    ]
