# Generated by Django 2.0 on 2018-05-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_remove_wallinformation_social_networks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='martialstatus',
            options={'verbose_name': 'Martial status', 'verbose_name_plural': 'Martial statuses'},
        ),
    ]
